
name: CI

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]
  workflow_dispatch:

jobs:
  lint-and-test:
    runs-on: ubuntu-latest
    timeout-minutes: 30
    strategy:
      matrix:
        python-version: ['3.11']
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}
          cache: 'pip'

      - name: Install dependencies (Airflow + providers + dev tools)
        run: |
          python -m pip install --upgrade pip
          pip install --no-cache-dir "apache-airflow==2.9.1"             --constraint "https://raw.githubusercontent.com/apache/airflow/constraints-2.9.1/constraints-${{ matrix.python-version }}.txt"
          pip install --no-cache-dir             confluent-kafka==2.4.0             apache-airflow-providers-apache-kafka==5.2.0             pytest pytest-cov             black==24.8.0 flake8==7.1.0

      - name: Lint (Black --check)
        run: black --check .

      - name: Lint (Flake8)
        run: flake8 .

      - name: Run tests with coverage
        run: |
          pytest --cov=dags --cov=tests                  --cov-report=xml                  --cov-report=term-missing                  --cov-fail-under=85

      - name: Upload coverage report
        uses: actions/upload-artifact@v4
        with:
          name: coverage-xml
          path: coverage.xml

  compose-validate:
    runs-on: ubuntu-latest
    if: ${{ always() }}
    steps:
      - uses: actions/checkout@v4
      - name: Validate docker-compose files
        run: |
          docker --version
          docker compose version || true
          docker compose -f docker-compose.yml config
          docker compose -f docker-compose.test.yml config
